
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Aug 15 01:55:18 BOT 2020
//----------------------------------------------------

package Code;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 34;
  public static final int Retorna = 25;
  public static final int PuntoComa = 32;
  public static final int Op_booleano = 35;
  public static final int If = 4;
  public static final int CierraLlave = 28;
  public static final int Dividir = 21;
  public static final int Diferente = 9;
  public static final int Potencia = 22;
  public static final int Clase = 2;
  public static final int Menor = 12;
  public static final int Else = 5;
  public static final int Variable = 30;
  public static final int Error = 33;
  public static final int Mayor = 10;
  public static final int Multiplicar = 19;
  public static final int CierraPar = 7;
  public static final int Division = 20;
  public static final int Int = 3;
  public static final int Asignar = 29;
  public static final int EOF = 0;
  public static final int AbreLlave = 27;
  public static final int error = 1;
  public static final int Imprimir = 26;
  public static final int Restar = 17;
  public static final int Access = 24;
  public static final int MenorIgual = 13;
  public static final int Identificador = 31;
  public static final int Resta = 16;
  public static final int Sumar = 15;
  public static final int MayorIgual = 11;
  public static final int Multiplicacion = 18;
  public static final int AbrePar = 6;
  public static final int Numero = 36;
  public static final int Suma = 14;
  public static final int Igual = 8;
  public static final int Elevar = 23;
}

